### PR TITLE
Feature/sw/ctp.alumni.survey

### PR DESCRIPTION
**Pull request by SamuelWitke**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

CUNY Tech prep  2021 alumni survey

## Related Tickets & Documents
Data Taken From https://docs.google.com/forms/d/e/1FAIpQLSeVMwkEs41Y9UQCNjxHYzvCp0FqOnFKl652PksooPJuG_7b4Q/viewform

## Mobile & Desktop Screenshots/Recordings
CUNY Tech Report

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
Added deployment step to the deploy action
```
          mv ./apps/ctp.alumni.survey/html ./apps/ctp.alumni.app/public/ctp.alumni.survey
```

## [optional] What gif best describes this PR or how it makes you feel?
Screen Shot 2021-10-14 at 9 02 19 AM

> That's a lot of changes. Can you edit the PR description with details of what's changed?

### CODE REVIEW

**Comment by SupaStuff** [comment]
That's a lot of changes. Can you edit the PR description with details of what's changed?

**Comment by SamuelWitke** [comment]
> That's a lot of changes. Can you edit the PR description with details of what's changed?

**Updated**
So my plan is to open source the masked responses from [CUNY Tech Prep Annual Alumni Survey (2021)](https://docs.google.com/forms/d/e/1FAIpQLSeVMwkEs41Y9UQCNjxHYzvCp0FqOnFKl652PksooPJuG_7b4Q/viewform).

I also want to host the jupyter lab file with [jupyterbook](http://jupyterbook.org/) so don't think we can make that apart of the github `Build and Deploy` step so might have to include the `dist` output as apart of the source. 

So everything from `apps/ctp.alumni.survey/html/2021AlumniSurvey.html` should be auto-generated.

**Review by SupaStuff — APPROVED** [review]
lgtm!

**Comment by SamuelWitke** [comment]
Drum roll
https://github.com/CUNYTechPrep/ctp.apps/runs/4191739866?check_suite_focus=true

**Pull request merged**
